### ISSUE TITLE
0

### ISSUE THREAD

**Issue by Hsgoplay** [Suto-Commune/soul_knight#2]

**Comment by Hsgoplay** [comment]
![Uploading QQ截图20240115113929.png…]()

**Comment by HaoTian22** [comment]
@Hsgoplay 你的报错截图没传上去

**Comment by Hsgoplay** [comment]
![QQ截图20240115113929](https://github.com/Suto-Commune/soul_knight/assets/137665106/7cd5603b-0b39-48f1-8640-1dc113d9c004)

**Comment by GooGuJiang** [comment]
你可以使用 `pip install crypto` 来安装一下看看

**Comment by Hsgoplay** [comment]
抱歉，可能我犯了一些非常低级的错误，但是我到现在没有看出来，麻烦您给我指出一下。我是用MuMu模拟器和mt管理器将这个item_data_125311101_.data 文件给进行导出，我在网上搜索如何解密的过程中看到了您的项目，因为我对这方面可能一窍不通，但我会上网上搜索一些，脑子能联想到的一些技术进行搜索学习之类的，我脑子可能反应不过来，麻烦您了

**Comment by GooGuJiang** [comment]
![Screenshot_2024-01-15-22-37-28-218-edit_com microsoft emmx dev](https://github.com/Suto-Commune/soul_knight/assets/74496778/fb11aadc-39b2-41a4-86d1-fe28514823f3)
抱歉，我并不是这个项目开发人员，所以具体细节我并不清楚，你可以更改一下文件路径指向 item_data_125311101_.data 文件位置，如上面截图所示（不一定对），或者等开发人员回复

**Comment by Hsgoplay** [comment]
抱歉抱歉，我是因为怕data后面那串数字影响到了程序，所以特意删除了，我现在更改了回来
![QQ截图20240115225046](https://github.com/Suto-Commune/soul_knight/assets/137665106/84b9ebd4-ae72-4738-b711-1f47dfae4b01)

**Comment by HaoTian22** [comment]
显然……是没装完包吧
请尝试执行`pip install requirements.txt -r`补全包，或者根据readme直接从pip安装这个软件

**Comment by HaoTian22** [comment]
另外py的路径需要用`/`或`\\`避免过度转义

**Comment by NatsumiXD** [comment]
> 您好，我是一个新手小白，我用idea打开您说的这个example.py文件，将item_data的文件路径按照您的方法放了上去，然后我直接运行报错了，不知道是我的操作有问题还是怎么回事，报红了，请您收到我的问题劳烦看一下，谢谢

如果你是从GitHub直接拉下来的应当把requirements里面的东西都安装上，但是事实上右侧有其pypi的连接，你可以通过pypi来安装

**Comment by NatsumiXD** [comment]
> ![QQ截图20240115113929](https://github.com/Suto-Commune/soul_knight/assets/137665106/7cd5603b-0b39-48f1-8640-1dc113d9c004)
> 

另外目录应当是「目录」，而不是文件名

**Comment by xzl0326** [comment]
> 你可以使用 `pip install crypto` 来安装一下看看

这东西好像新版的Python安装不上
