### ISSUE TITLE
找不到.data/.byte的文件

### ISSUE THREAD

**Issue by yueee69** [Suto-Commune/soul_knight#3]
![image](https://github.com/Suto-Commune/soul_knight/assets/124560527/c43afb00-2e88-43a7-871b-5634434d499a)
已經到指定目錄files下找.data/.byte的文件 但似乎都沒有找到:( 直接貼上路徑(files/game.data)也會錯誤(系統找不到這個檔案) 是哪裡出問題了?

**Comment by NatsumiXD** [comment]
文件处于/data/data下，您需要拥有root权限才能提取
